apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubernetes.io/description: Contains the GitHub actions-runner-controller operator.
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: arc-system
spec: {}
