apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-dto-btn-arc-private-runners
  annotations:
    kubernetes.io/descripton: "Holds the secrets of the dto-btn-arc-private-runners GitHub app used by the actions-runner-controller."
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: &key /canchat-non-prod-ns-qffdc/canchat-non-prod
      property: github-app-arc-private-runners-id
      metadataPolicy: None
    secretKey: github_app_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: *key
      property: github-app-arc-private-runners-installation-id-dto-btn
      metadataPolicy: None
    secretKey: github_app_installation_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Auto
      key: *key
      property: github-app-arc-private-runners-private-key-base64
      metadataPolicy: None
    secretKey: github_app_private_key
  refreshInterval: "1h0m0s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: canchat-non-prod-vcf-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
