apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-volumes
spec:
  storageClassName: vcfa-tenant
  resources:
    requests:
      storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce