apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dto-btn/aips-cluster.git
    path: charts/cert-manager-config
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
