# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: enterprise-knowledge-hub
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/dto-btn/enterprise-knowledge-hub.git
#     path: deployments/ekh
#     targetRevision: main
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: ekh-prod
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true