apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-azuredns
spec:
  acme:
    email: guillaume.turcotte2@ssc-spc.gc.ca
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            hostedZoneName: ssc-prod-cioassistant.g3.ent.cloud-nuage.canada.ca
            resourceGroupName: G3Pc-SSC_CIOAssistant_DNS-rg
            subscriptionID: dd7b6f23-7cf4-4598-a0ba-55888cfb1616
            managedIdentity:
              clientID: 7c436f49-e3ea-4749-a4f1-a39471f4b2a0
