apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name traefik
  namespace: &env aips-platform
spec:
  destination:
    namespace: *name
    server: https://kubernetes.default.svc
  project: *env
  sources:
  - helm:
      releaseName: *name
      valueFiles:
      - $values/platform/traefik/values.yaml
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.4.0
  - repoURL: &iacRepo 'https://github.com/dto-btn/aips-cluster'
    targetRevision: &iacTargetRevision main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true