apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubernetes.io/description: Contains GitHub Actions Runner configuration for dto-btn.
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: arc-runner-dto-btn
spec: {}
