# This was installed manually without argo.  
# So adding it now means this will need to match exactly as our current installation. 
# To bootstrap, we can use helm defaults with the changes below.  
acmesolver:
  image:
    name: cert-manager-acmesolver
    pullPolicy: IfNotPresent
    repository: ""
  runtimeClassName: ""
affinity: {}
approveSignerNames:
- issuers.cert-manager.io/*
- clusterissuers.cert-manager.io/*
cainjector:
  affinity: {}
  config: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  enableServiceLinks: false
  enabled: true
  extraArgs: []
  extraEnv: []
  featureGates: ""
  image:
    name: cert-manager-cainjector
    pullPolicy: IfNotPresent
    repository: ""
  networkPolicy:
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
      - port: 6443
        protocol: TCP
    enabled: false
    ingress:
    - ports:
      - port: http-metrics
        protocol: TCP
  nodeSelector:
    kubernetes.io/os: linux
  podDisruptionBudget:
    enabled: false
  podLabels: {}
  replicaCount: 1
  resources: {}
  runtimeClassName: ""
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    automountServiceAccountToken: true
    create: true
  serviceLabels: {}
  strategy: {}
  tolerations: []
  topologySpreadConstraints: []
  volumeMounts: []
  volumes: []
clusterResourceNamespace: ""
config: {}
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
crds:
  enabled: true
  keep: true
creator: helm
disableAutoApproval: false
dns01RecursiveNameservers: ""
dns01RecursiveNameserversOnly: false
enableCertificateOwnerRef: false
enableServiceLinks: false
enabled: true
extraArgs: []
extraContainers: []
extraEnv:
- name: SSL_CERT_FILE
  value: /etc/ssl/certs/ca-bundle.crt
extraObjects: []
featureGates: ""
global:
  commonLabels: {}
  imagePullSecrets: []
  leaderElection:
    namespace: kube-system
  logLevel: 2
  nodeSelector: {}
  podSecurityPolicy:
    enabled: false
    useAppArmor: true
  priorityClassName: ""
  rbac:
    aggregateClusterRoles: true
    create: true
  runtimeClassName: ""
hostAliases: []
image:
  name: cert-manager-controller
  pullPolicy: IfNotPresent
  repository: ""
imageNamespace: jetstack
imageRegistry: quay.io
ingressShim: {}
installCRDs: false
livenessProbe:
  enabled: true
  failureThreshold: 8
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
maxConcurrentChallenges: 60
namespace: ""
networkPolicy:
  egress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 6443
      protocol: TCP
  enabled: false
  ingress:
  - ports:
    - port: http-metrics
      protocol: TCP
    - port: http-healthz
      protocol: TCP
nodeSelector:
  kubernetes.io/os: linux
podDisruptionBudget:
  enabled: false
podLabels: {}
prometheus:
  enabled: true
  podmonitor:
    annotations: {}
    enabled: false
    endpointAdditionalProperties: {}
    honorLabels: false
    interval: 60s
    labels: {}
    prometheusInstance: default
    scrapeTimeout: 30s
  servicemonitor:
    annotations: {}
    enabled: false
    endpointAdditionalProperties: {}
    honorLabels: false
    interval: 60s
    labels: {}
    prometheusInstance: default
    scrapeTimeout: 30s
replicaCount: 1
resources: {}
runtimeClassName: ""
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  automountServiceAccountToken: true
  create: true
startupapicheck:
  affinity: {}
  backoffLimit: 4
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  enableServiceLinks: false
  enabled: true
  extraArgs:
  - -v
  extraEnv: []
  image:
    name: cert-manager-startupapicheck
    pullPolicy: IfNotPresent
    repository: ""
  jobAnnotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
  nodeSelector:
    kubernetes.io/os: linux
  podLabels: {}
  rbac:
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
      helm.sh/hook-weight: "-5"
  resources: {}
  runtimeClassName: ""
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
      helm.sh/hook-weight: "-5"
    automountServiceAccountToken: true
    create: true
  timeout: 1m
  tolerations: []
  volumeMounts: []
  volumes: []
strategy: {}
tolerations: []
topologySpreadConstraints: []
volumeMounts:
- mountPath: /etc/ssl/certs/ca-bundle.crt
  name: ca-bundle
  readOnly: true
  subPath: ca-bundle.crt
volumes:
- configMap:
    defaultMode: 420
    name: aips-trust-bundle
  name: ca-bundle
webhook:
  affinity: {}
  apiserverClientCertSubjects: ""
  clientCAFile: ""
  config: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  enableClientVerification: false
  enableServiceLinks: false
  extraArgs: []
  extraEnv: []
  featureGates: ""
  hostNetwork: false
  image:
    name: cert-manager-webhook
    pullPolicy: IfNotPresent
    repository: ""
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  mutatingWebhookConfiguration:
    namespaceSelector: {}
  networkPolicy:
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
      - port: 6443
        protocol: TCP
    enabled: false
    ingress:
    - ports:
      - port: https
        protocol: TCP
      - port: healthcheck
        protocol: TCP
      - port: http-metrics
        protocol: TCP
  nodeSelector:
    kubernetes.io/os: linux
  podDisruptionBudget:
    enabled: false
  podLabels: {}
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources: {}
  runtimeClassName: ""
  securePort: 10250
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    automountServiceAccountToken: true
    create: true
  serviceIPFamilies: []
  serviceIPFamilyPolicy: ""
  serviceLabels: {}
  serviceType: ClusterIP
  strategy: {}
  timeoutSeconds: 30
  tolerations: []
  topologySpreadConstraints: []
  url: {}
  validatingWebhookConfiguration:
    namespaceSelector:
      matchExpressions:
      - key: cert-manager.io/disable-validation
        operator: NotIn
        values:
        - "true"
  volumeMounts: []
  volumes: []