# This was installed manually without argo.  
# So adding it now means this will need to match exactly as our current installation. 
# To bootstrap, we can use helm defaults with the changes below.  
crds:
  enabled: true

dns01RecursiveNameservers: "172.31.144.1:53"
dns01RecursiveNameserversOnly: true

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "7c436f49-e3ea-4749-a4f1-a39471f4b2a0"

podLabels:
  azure.workload.identity/use: "true"

extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/ca-bundle.crt

volumes:
  - name: ca-bundle
    configMap:
      name: aips-trust-bundle
      defaultMode: 0644

volumeMounts:
  - name: ca-bundle
    mountPath: /etc/ssl/certs/ca-bundle.crt
    subPath: ca-bundle.crt
    readOnly: true
