# This was installed manually without argo.  
# So adding it now means this will need to match exactly as our current installation. 
# To bootstrap, we can use helm defaults with the changes below.  
crds:
  enabled: true

extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/ca-bundle.crt

volumes:
  - name: ca-bundle
    configMap:
      name: aips-trust-bundle
      defaultMode: 0644

volumeMounts:
  - name: ca-bundle
    mountPath: /etc/ssl/certs/ca-bundle.crt
    subPath: ca-bundle.crt
    readOnly: true
