apiVersion: external-secrets.io/v1beta1
# This file is random.  added for git to create manifest folder, to resolve manifest folder can't be found error
kind: ExternalSecret
metadata:
  name: argocd-oidc-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: REPLACE_WITH_CLUSTER_SECRET_STORE
  target:
    name: argocd-oidc-secrets
    creationPolicy: Owner
  data:
  - secretKey: oidc.azure.163gc.client-id
    remoteRef:
      key: REPLACE_WITH_REMOTE_SECRET_KEY
      property: client_id
  - secretKey: oidc.azure.163gc.client-secret
    remoteRef:
      key: REPLACE_WITH_REMOTE_SECRET_KEY
      property: client_secret
  - secretKey: oidc.azure.163gc.client-issuer-url
    remoteRef:
      key: REPLACE_WITH_REMOTE_SECRET_KEY
      property: client_issuer_url
