apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: &project actions-runners
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project for cluster-wide or shared resources.
  destinations:
  - name: in-cluster
    namespace: *project
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: canchat-platform
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - *project
  sourceRepos:
  - https://github.com/dto-btn/aips-cluster
  - oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  - oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  - https://charts.external-secrets.io
