apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    kubernetes.io/description: A ClusterSecretStore which provides access to the Azure
      KeyVault named eso-argocd-4519-kv
  name: eso-argocd-4519-kv
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://eso-argocd-4519-kv.vault.azure.net/"
      serviceAccountRef:
        name: workload-identity-sa


  # provider:
  #   azurekv:
  #     authSecretRef:
  #       clientId:
  #         key: clientId
  #     authType: ManagedIdentity
  #     environmentType: PublicCloud
  #     tenantId: 7198d08c-c362-4703-9854-53b6f0d8fc44
  #     useAzureSDK: false
  #     vaultUrl: https://eso-argocd-4519-kv.vault.azure.net/
